
version: 2

sources:
  - name: raw
    database: DBT_DEMO
    schema: RAW

    tables:
      - name: CUSTOMERS
      - name: EMPLOYEES

models:
  - name: Customers
    description: "Customer model"

    columns:
      - name: ID
        tests:
          - unique
          - not_null
    
  - name: Employees
    description: "Employees model"
        
